#!/usr/local/bin/expect -f
proc power_on {device_name} {
	if {[catch {exec devpowerctl restart $device_name}]} {
		puts stderr "An error occured restarting $device_name."
		exit 1
	}
}

proc power_off {device_name} {
	if {[catch {exec devpowerctl turn_off $device_name}]} {
		puts stderr "An error occured restarting $device_name."
		exit 1
	}
}

proc handle_err {device_name err_msg} {
	send_log "ERROR: $err_msg"
	power_off $device_name
	exit 1
}


